source "https://rubygems.org"

# assets
gem "sass",           "~> 3.2.14"
gem "uglifier",       "~> 2.2.1"
gem "coffee-script",  "~> 2.2.0"

# util
gem "therubyracer",   "~> 0.12.0"
gem "rake",           "~> 10.1.0"
gem "colorize",       "~> 0.6.0"
gem "borrower",       "~> 0.7.0"

# guard
gem "guard",          "~> 1.8.3"
gem "guard-shell",    "~> 0.5.1"